# Generated by Django 5.2.8 on 2025-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='urlconf',
            field=models.CharField(blank=True, default='myproject.dashboard_urls', max_length=256, null=True),
        ),
    ]
