# Generated by Django 5.2.8 on 2025-11-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_urlconf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='urlconf',
        ),
    ]
